package com.bank.islamic.paymentorder;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Payment Order
 *
 * Business Area:      Takaful and Shared Operations
 * Business Domain:    Islamic Cards and Payments
 * Functional Pattern: Process
 * Asset Type:         Payment Order
 * Control Record:     Payment Order Procedure
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Payment Order — BIAN Semantic API")
                .description("Service Domain 'Payment Order' (Process pattern) "
                        + "operating on the 'Payment Order Procedure' control record.")
                .version("0.1.0"));
    }
}
